version: '2'

services: 
    postgres:
        container_name: postgres
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=dlgjgx
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes: 
            - /data/pg_data/data:/var/lib/postgresql/data/pgdata
        ports: 
            - "5432:5432"