version: '2'

networks: 
  test:

services: 
  mongodb0:
    container_name: mongodb0
    image: mongo:4.4.2
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports: 
      - 27017:27017
    networks: 
      - test